// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgxS3kJVxYk5z-y1TFj-QTmwrQCxCUFtQ',
    appId: '1:248826165993:web:9234138fd1d540d552ce78',
    messagingSenderId: '248826165993',
    projectId: 'eatme-8ef35',
    authDomain: 'eatme-8ef35.firebaseapp.com',
    storageBucket: 'eatme-8ef35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUABRhkzpezdnS_ux5MA2vWWXMskO-rxA',
    appId: '1:248826165993:android:8071aff3628b1beb52ce78',
    messagingSenderId: '248826165993',
    projectId: 'eatme-8ef35',
    storageBucket: 'eatme-8ef35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhATrEimtPoQpcifCyS6t-onHZZeZg3nw',
    appId: '1:248826165993:ios:25823ac15838c52552ce78',
    messagingSenderId: '248826165993',
    projectId: 'eatme-8ef35',
    storageBucket: 'eatme-8ef35.appspot.com',
    iosClientId: '248826165993-fehn35bh3tbtpqskjmrfn0uc8amp9bav.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhATrEimtPoQpcifCyS6t-onHZZeZg3nw',
    appId: '1:248826165993:ios:ff835afd143cf1f452ce78',
    messagingSenderId: '248826165993',
    projectId: 'eatme-8ef35',
    storageBucket: 'eatme-8ef35.appspot.com',
    iosClientId: '248826165993-r5nrd9000pvcs51a5a7qdqdsp6c7rnf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatme.RunnerTests',
  );
}
